apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720488407518:role/NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::720488407518:role/aims-eks-deploy-codebuild-role
      username: codebuild-eks
      groups:
        - system:masters
