apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::720488407518:role/NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes      
    - rolearn: arn:aws:iam::720488407518:role/codebuild-eks
      username: codebuild-eks
      groups:
        - system:masters        
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system